window.esdocSearchIndex = [
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "packages/api-gateway/coverage/lcov-report/prettify.js",
    "file/packages/api-gateway/coverage/lcov-report/prettify.js.html",
    "packages/api-gateway/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/api-gateway/coverage/lcov-report/sorter.js",
    "file/packages/api-gateway/coverage/lcov-report/sorter.js.html",
    "packages/api-gateway/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/api-gateway/src/api.js",
    "file/packages/api-gateway/src/api.js.html",
    "packages/api-gateway/src/api.js",
    "file"
  ],
  [
    "packages/api-gateway/src/aws-policies.js",
    "file/packages/api-gateway/src/aws-policies.js.html",
    "packages/api-gateway/src/aws-policies.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/create-api.js",
    "file/packages/api-gateway/src/cli/create-api.js.html",
    "packages/api-gateway/src/cli/create-api.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/create-endpoint.js",
    "file/packages/api-gateway/src/cli/create-endpoint.js.html",
    "packages/api-gateway/src/cli/create-endpoint.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/create-model.js",
    "file/packages/api-gateway/src/cli/create-model.js.html",
    "packages/api-gateway/src/cli/create-model.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/deploy-apis.js",
    "file/packages/api-gateway/src/cli/deploy-apis.js.html",
    "packages/api-gateway/src/cli/deploy-apis.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/inspect-api.js",
    "file/packages/api-gateway/src/cli/inspect-api.js.html",
    "packages/api-gateway/src/cli/inspect-api.js",
    "file"
  ],
  [
    "packages/api-gateway/src/cli/inspect-endpoint.js",
    "file/packages/api-gateway/src/cli/inspect-endpoint.js.html",
    "packages/api-gateway/src/cli/inspect-endpoint.js",
    "file"
  ],
  [
    "packages/api-gateway/src/endpoint.js",
    "file/packages/api-gateway/src/endpoint.js.html",
    "packages/api-gateway/src/endpoint.js",
    "file"
  ],
  [
    "packages/api-gateway/src/index.js",
    "file/packages/api-gateway/src/index.js.html",
    "packages/api-gateway/src/index.js",
    "file"
  ],
  [
    "packages/api-gateway/src/model.js",
    "file/packages/api-gateway/src/model.js.html",
    "packages/api-gateway/src/model.js",
    "file"
  ],
  [
    "packages/api-gateway/test-assets/endpoints/delivery/delete/index.js",
    "file/packages/api-gateway/test-assets/endpoints/delivery/DELETE/index.js.html",
    "packages/api-gateway/test-assets/endpoints/delivery/DELETE/index.js",
    "file"
  ],
  [
    "packages/api-gateway/test-assets/endpoints/delivery/get/index.js",
    "file/packages/api-gateway/test-assets/endpoints/delivery/GET/index.js.html",
    "packages/api-gateway/test-assets/endpoints/delivery/GET/index.js",
    "file"
  ],
  [
    "packages/api-gateway/test-assets/endpoints/delivery/patch/index.js",
    "file/packages/api-gateway/test-assets/endpoints/delivery/PATCH/index.js.html",
    "packages/api-gateway/test-assets/endpoints/delivery/PATCH/index.js",
    "file"
  ],
  [
    "packages/api-gateway/test-assets/endpoints/delivery/put/index.js",
    "file/packages/api-gateway/test-assets/endpoints/delivery/PUT/index.js.html",
    "packages/api-gateway/test-assets/endpoints/delivery/PUT/index.js",
    "file"
  ],
  [
    "packages/api-gateway/test/__bootstrap.test.js",
    "file/packages/api-gateway/test/__bootstrap.test.js.html",
    "packages/api-gateway/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/api.test.js",
    "file/packages/api-gateway/test/api.test.js.html",
    "packages/api-gateway/test/api.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/create-api.test.js",
    "file/packages/api-gateway/test/cli/create-api.test.js.html",
    "packages/api-gateway/test/cli/create-api.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/create-endpoint.test.js",
    "file/packages/api-gateway/test/cli/create-endpoint.test.js.html",
    "packages/api-gateway/test/cli/create-endpoint.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/create-model.test.js",
    "file/packages/api-gateway/test/cli/create-model.test.js.html",
    "packages/api-gateway/test/cli/create-model.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/deploy-apis.test.js",
    "file/packages/api-gateway/test/cli/deploy-apis.test.js.html",
    "packages/api-gateway/test/cli/deploy-apis.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/inspect-api.test.js",
    "file/packages/api-gateway/test/cli/inspect-api.test.js.html",
    "packages/api-gateway/test/cli/inspect-api.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/cli/inspect-endpoint.test.js",
    "file/packages/api-gateway/test/cli/inspect-endpoint.test.js.html",
    "packages/api-gateway/test/cli/inspect-endpoint.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/endpoint.test.js",
    "file/packages/api-gateway/test/endpoint.test.js.html",
    "packages/api-gateway/test/endpoint.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/index.test.js",
    "file/packages/api-gateway/test/index.test.js.html",
    "packages/api-gateway/test/index.test.js",
    "file"
  ],
  [
    "packages/api-gateway/test/model.test.js",
    "file/packages/api-gateway/test/model.test.js.html",
    "packages/api-gateway/test/model.test.js",
    "file"
  ],
  [
    "packages/cli/coverage/lcov-report/prettify.js",
    "file/packages/cli/coverage/lcov-report/prettify.js.html",
    "packages/cli/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/cli/coverage/lcov-report/sorter.js",
    "file/packages/cli/coverage/lcov-report/sorter.js.html",
    "packages/cli/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/cli/src/cli/cheers.js",
    "file/packages/cli/src/cli/cheers.js.html",
    "packages/cli/src/cli/cheers.js",
    "file"
  ],
  [
    "packages/cli/src/cli/disable-default.js",
    "file/packages/cli/src/cli/disable-default.js.html",
    "packages/cli/src/cli/disable-default.js",
    "file"
  ],
  [
    "packages/cli/src/cli/figlet/lib/figlet.js",
    "file/packages/cli/src/cli/figlet/lib/figlet.js.html",
    "packages/cli/src/cli/figlet/lib/figlet.js",
    "file"
  ],
  [
    "packages/cli/src/cli/figlet/lib/node-figlet.js",
    "file/packages/cli/src/cli/figlet/lib/node-figlet.js.html",
    "packages/cli/src/cli/figlet/lib/node-figlet.js",
    "file"
  ],
  [
    "packages/cli/src/cli/new.js",
    "file/packages/cli/src/cli/new.js.html",
    "packages/cli/src/cli/new.js",
    "file"
  ],
  [
    "packages/cli/src/cli/show-config.js",
    "file/packages/cli/src/cli/show-config.js.html",
    "packages/cli/src/cli/show-config.js",
    "file"
  ],
  [
    "packages/cli/src/commander-help-override.js",
    "file/packages/cli/src/commander-help-override.js.html",
    "packages/cli/src/commander-help-override.js",
    "file"
  ],
  [
    "packages/cli/src/load-project.js",
    "file/packages/cli/src/load-project.js.html",
    "packages/cli/src/load-project.js",
    "file"
  ],
  [
    "packages/cli/src/test/__bootstrap.test.js",
    "file/packages/cli/src/test/__bootstrap.test.js.html",
    "packages/cli/src/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/cli/src/test/cli/cheers.test.js",
    "file/packages/cli/src/test/cli/cheers.test.js.html",
    "packages/cli/src/test/cli/cheers.test.js",
    "file"
  ],
  [
    "packages/cli/src/test/cli/disable-default.test.js",
    "file/packages/cli/src/test/cli/disable-default.test.js.html",
    "packages/cli/src/test/cli/disable-default.test.js",
    "file"
  ],
  [
    "packages/cli/src/test/cli/new.test.js",
    "file/packages/cli/src/test/cli/new.test.js.html",
    "packages/cli/src/test/cli/new.test.js",
    "file"
  ],
  [
    "packages/cli/src/test/command-help-override.test.js",
    "file/packages/cli/src/test/command-help-override.test.js.html",
    "packages/cli/src/test/command-help-override.test.js",
    "file"
  ],
  [
    "packages/cli/src/test/load-project.test.js",
    "file/packages/cli/src/test/load-project.test.js.html",
    "packages/cli/src/test/load-project.test.js",
    "file"
  ],
  [
    "packages/cli/test-assets/plugins/hello.js",
    "file/packages/cli/test-assets/plugins/hello.js.html",
    "packages/cli/test-assets/plugins/hello.js",
    "file"
  ],
  [
    "packages/cli/test-assets/plugins/world/index.js",
    "file/packages/cli/test-assets/plugins/world/index.js.html",
    "packages/cli/test-assets/plugins/world/index.js",
    "file"
  ],
  [
    "packages/cli/test/__bootstrap.test.js",
    "file/packages/cli/test/__bootstrap.test.js.html",
    "packages/cli/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/cli/test/cli/disable-default.test.js",
    "file/packages/cli/test/cli/disable-default.test.js.html",
    "packages/cli/test/cli/disable-default.test.js",
    "file"
  ],
  [
    "packages/cli/test/cli/new.test.js",
    "file/packages/cli/test/cli/new.test.js.html",
    "packages/cli/test/cli/new.test.js",
    "file"
  ],
  [
    "packages/cli/test/cli/please.test.js",
    "file/packages/cli/test/cli/please.test.js.html",
    "packages/cli/test/cli/please.test.js",
    "file"
  ],
  [
    "packages/cli/test/command-help-override.test.js",
    "file/packages/cli/test/command-help-override.test.js.html",
    "packages/cli/test/command-help-override.test.js",
    "file"
  ],
  [
    "packages/cli/test/load-project.test.js",
    "file/packages/cli/test/load-project.test.js.html",
    "packages/cli/test/load-project.test.js",
    "file"
  ],
  [
    "packages/core/coverage/lcov-report/prettify.js",
    "file/packages/core/coverage/lcov-report/prettify.js.html",
    "packages/core/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/core/coverage/lcov-report/sorter.js",
    "file/packages/core/coverage/lcov-report/sorter.js.html",
    "packages/core/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/core/src/lib/log.js",
    "file/packages/core/src/lib/log.js.html",
    "packages/core/src/lib/log.js",
    "file"
  ],
  [
    "packages/core/src/lib/myrmex.js",
    "file/packages/core/src/lib/myrmex.js.html",
    "packages/core/src/lib/myrmex.js",
    "file"
  ],
  [
    "packages/core/test/__bootstrap.test.js",
    "file/packages/core/test/__bootstrap.test.js.html",
    "packages/core/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/core/test/lib/lager.test.js",
    "file/packages/core/test/lib/lager.test.js.html",
    "packages/core/test/lib/lager.test.js",
    "file"
  ],
  [
    "packages/cors/coverage/lcov-report/prettify.js",
    "file/packages/cors/coverage/lcov-report/prettify.js.html",
    "packages/cors/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/cors/coverage/lcov-report/sorter.js",
    "file/packages/cors/coverage/lcov-report/sorter.js.html",
    "packages/cors/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/cors/src/hooks/after-add-endpoints-to-api.js",
    "file/packages/cors/src/hooks/after-add-endpoints-to-api.js.html",
    "packages/cors/src/hooks/after-add-endpoints-to-api.js",
    "file"
  ],
  [
    "packages/cors/src/index.js",
    "file/packages/cors/src/index.js.html",
    "packages/cors/src/index.js",
    "file"
  ],
  [
    "packages/cors/test/__bootstrap.test.js",
    "file/packages/cors/test/__bootstrap.test.js.html",
    "packages/cors/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/iam/coverage/lcov-report/prettify.js",
    "file/packages/iam/coverage/lcov-report/prettify.js.html",
    "packages/iam/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/iam/coverage/lcov-report/sorter.js",
    "file/packages/iam/coverage/lcov-report/sorter.js.html",
    "packages/iam/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/iam/src/cli/create-policy.js",
    "file/packages/iam/src/cli/create-policy.js.html",
    "packages/iam/src/cli/create-policy.js",
    "file"
  ],
  [
    "packages/iam/src/cli/create-role.js",
    "file/packages/iam/src/cli/create-role.js.html",
    "packages/iam/src/cli/create-role.js",
    "file"
  ],
  [
    "packages/iam/src/cli/deploy-policies.js",
    "file/packages/iam/src/cli/deploy-policies.js.html",
    "packages/iam/src/cli/deploy-policies.js",
    "file"
  ],
  [
    "packages/iam/src/cli/deploy-roles.js",
    "file/packages/iam/src/cli/deploy-roles.js.html",
    "packages/iam/src/cli/deploy-roles.js",
    "file"
  ],
  [
    "packages/iam/src/helper.js",
    "file/packages/iam/src/helper.js.html",
    "packages/iam/src/helper.js",
    "file"
  ],
  [
    "packages/iam/src/hooks/create-command.js",
    "file/packages/iam/src/hooks/create-command.js.html",
    "packages/iam/src/hooks/create-command.js",
    "file"
  ],
  [
    "packages/iam/src/index.js",
    "file/packages/iam/src/index.js.html",
    "packages/iam/src/index.js",
    "file"
  ],
  [
    "packages/iam/src/policy.js",
    "file/packages/iam/src/policy.js.html",
    "packages/iam/src/policy.js",
    "file"
  ],
  [
    "packages/iam/src/role.js",
    "file/packages/iam/src/role.js.html",
    "packages/iam/src/role.js",
    "file"
  ],
  [
    "packages/iam/test/__bootstrap.test.js",
    "file/packages/iam/test/__bootstrap.test.js.html",
    "packages/iam/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/iam/test/cli/create-policy.test.js",
    "file/packages/iam/test/cli/create-policy.test.js.html",
    "packages/iam/test/cli/create-policy.test.js",
    "file"
  ],
  [
    "packages/iam/test/cli/create-role.test.js",
    "file/packages/iam/test/cli/create-role.test.js.html",
    "packages/iam/test/cli/create-role.test.js",
    "file"
  ],
  [
    "packages/iam/test/cli/deploy-policies.test.js",
    "file/packages/iam/test/cli/deploy-policies.test.js.html",
    "packages/iam/test/cli/deploy-policies.test.js",
    "file"
  ],
  [
    "packages/iam/test/cli/deploy-roles.test.js",
    "file/packages/iam/test/cli/deploy-roles.test.js.html",
    "packages/iam/test/cli/deploy-roles.test.js",
    "file"
  ],
  [
    "packages/iam/test/index.test.js",
    "file/packages/iam/test/index.test.js.html",
    "packages/iam/test/index.test.js",
    "file"
  ],
  [
    "packages/iam/test/policy.test.js",
    "file/packages/iam/test/policy.test.js.html",
    "packages/iam/test/policy.test.js",
    "file"
  ],
  [
    "packages/iam/test/role.test.js",
    "file/packages/iam/test/role.test.js.html",
    "packages/iam/test/role.test.js",
    "file"
  ],
  [
    "packages/lambda/coverage/lcov-report/prettify.js",
    "file/packages/lambda/coverage/lcov-report/prettify.js.html",
    "packages/lambda/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/lambda/coverage/lcov-report/sorter.js",
    "file/packages/lambda/coverage/lcov-report/sorter.js.html",
    "packages/lambda/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/lambda/src/aws-policies.js",
    "file/packages/lambda/src/aws-policies.js.html",
    "packages/lambda/src/aws-policies.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/create-lambda.js",
    "file/packages/lambda/src/cli/create-lambda.js.html",
    "packages/lambda/src/cli/create-lambda.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/create-node-module.js",
    "file/packages/lambda/src/cli/create-node-module.js.html",
    "packages/lambda/src/cli/create-node-module.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/deploy-lambdas.js",
    "file/packages/lambda/src/cli/deploy-lambdas.js.html",
    "packages/lambda/src/cli/deploy-lambdas.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/install-lambdas-locally.js",
    "file/packages/lambda/src/cli/install-lambdas-locally.js.html",
    "packages/lambda/src/cli/install-lambdas-locally.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/templates/index.js",
    "file/packages/lambda/src/cli/templates/index.js.html",
    "packages/lambda/src/cli/templates/index.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/test-lambda-locally.js",
    "file/packages/lambda/src/cli/test-lambda-locally.js.html",
    "packages/lambda/src/cli/test-lambda-locally.js",
    "file"
  ],
  [
    "packages/lambda/src/cli/test-lambda.js",
    "file/packages/lambda/src/cli/test-lambda.js.html",
    "packages/lambda/src/cli/test-lambda.js",
    "file"
  ],
  [
    "packages/lambda/src/hooks/create-command.js",
    "file/packages/lambda/src/hooks/create-command.js.html",
    "packages/lambda/src/hooks/create-command.js",
    "file"
  ],
  [
    "packages/lambda/src/hooks/load-integration.js",
    "file/packages/lambda/src/hooks/load-integration.js.html",
    "packages/lambda/src/hooks/load-integration.js",
    "file"
  ],
  [
    "packages/lambda/src/index.js",
    "file/packages/lambda/src/index.js.html",
    "packages/lambda/src/index.js",
    "file"
  ],
  [
    "packages/lambda/src/integration-data-injector.js",
    "file/packages/lambda/src/integration-data-injector.js.html",
    "packages/lambda/src/integration-data-injector.js",
    "file"
  ],
  [
    "packages/lambda/src/lambda-runtime/nodejs-context-mock.js",
    "file/packages/lambda/src/lambda-runtime/nodejs-context-mock.js.html",
    "packages/lambda/src/lambda-runtime/nodejs-context-mock.js",
    "file"
  ],
  [
    "packages/lambda/src/lambda-runtime/nodejs.js",
    "file/packages/lambda/src/lambda-runtime/nodejs.js.html",
    "packages/lambda/src/lambda-runtime/nodejs.js",
    "file"
  ],
  [
    "packages/lambda/src/lambda-runtime/python.js",
    "file/packages/lambda/src/lambda-runtime/python.js.html",
    "packages/lambda/src/lambda-runtime/python.js",
    "file"
  ],
  [
    "packages/lambda/src/lambda.js",
    "file/packages/lambda/src/lambda.js.html",
    "packages/lambda/src/lambda.js",
    "file"
  ],
  [
    "packages/lambda/src/node-module.js",
    "file/packages/lambda/src/node-module.js.html",
    "packages/lambda/src/node-module.js",
    "file"
  ],
  [
    "packages/lambda/src/tools/generate-reports-table.js",
    "file/packages/lambda/src/tools/generate-reports-table.js.html",
    "packages/lambda/src/tools/generate-reports-table.js",
    "file"
  ],
  [
    "packages/lambda/test-assets/lambdas/callback-lambda/lambda.js",
    "file/packages/lambda/test-assets/lambdas/callback-lambda/lambda.js.html",
    "packages/lambda/test-assets/lambdas/callback-lambda/lambda.js",
    "file"
  ],
  [
    "packages/lambda/test-assets/lambdas/context-lambda/lambda.js",
    "file/packages/lambda/test-assets/lambdas/context-lambda/lambda.js.html",
    "packages/lambda/test-assets/lambdas/context-lambda/lambda.js",
    "file"
  ],
  [
    "packages/lambda/test-assets/lambdas/empty-lambda/lambda.js",
    "file/packages/lambda/test-assets/lambdas/empty-lambda/lambda.js.html",
    "packages/lambda/test-assets/lambdas/empty-lambda/lambda.js",
    "file"
  ],
  [
    "packages/lambda/test-assets/modules/data-access/index.js",
    "file/packages/lambda/test-assets/modules/data-access/index.js.html",
    "packages/lambda/test-assets/modules/data-access/index.js",
    "file"
  ],
  [
    "packages/lambda/test-assets/modules/log/index.js",
    "file/packages/lambda/test-assets/modules/log/index.js.html",
    "packages/lambda/test-assets/modules/log/index.js",
    "file"
  ],
  [
    "packages/lambda/test/__bootstrap.test.js",
    "file/packages/lambda/test/__bootstrap.test.js.html",
    "packages/lambda/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/create-lambda.test.js",
    "file/packages/lambda/test/cli/create-lambda.test.js.html",
    "packages/lambda/test/cli/create-lambda.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/create-node-module.test.js",
    "file/packages/lambda/test/cli/create-node-module.test.js.html",
    "packages/lambda/test/cli/create-node-module.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/deploy-lambdas.test.js",
    "file/packages/lambda/test/cli/deploy-lambdas.test.js.html",
    "packages/lambda/test/cli/deploy-lambdas.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/install-lambdas-locally.test.js",
    "file/packages/lambda/test/cli/install-lambdas-locally.test.js.html",
    "packages/lambda/test/cli/install-lambdas-locally.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/test-lambda-locally.test.js",
    "file/packages/lambda/test/cli/test-lambda-locally.test.js.html",
    "packages/lambda/test/cli/test-lambda-locally.test.js",
    "file"
  ],
  [
    "packages/lambda/test/cli/test-lambda.test.js",
    "file/packages/lambda/test/cli/test-lambda.test.js.html",
    "packages/lambda/test/cli/test-lambda.test.js",
    "file"
  ],
  [
    "packages/lambda/test/index.test.js",
    "file/packages/lambda/test/index.test.js.html",
    "packages/lambda/test/index.test.js",
    "file"
  ],
  [
    "packages/lambda/test/integration-data-injector.test.js",
    "file/packages/lambda/test/integration-data-injector.test.js.html",
    "packages/lambda/test/integration-data-injector.test.js",
    "file"
  ],
  [
    "packages/lambda/test/lambda.test.js",
    "file/packages/lambda/test/lambda.test.js.html",
    "packages/lambda/test/lambda.test.js",
    "file"
  ],
  [
    "packages/packager/coverage/lcov-report/prettify.js",
    "file/packages/packager/coverage/lcov-report/prettify.js.html",
    "packages/packager/coverage/lcov-report/prettify.js",
    "file"
  ],
  [
    "packages/packager/coverage/lcov-report/sorter.js",
    "file/packages/packager/coverage/lcov-report/sorter.js.html",
    "packages/packager/coverage/lcov-report/sorter.js",
    "file"
  ],
  [
    "packages/packager/src/hooks/build-lambda-package.js",
    "file/packages/packager/src/hooks/build-lambda-package.js.html",
    "packages/packager/src/hooks/build-lambda-package.js",
    "file"
  ],
  [
    "packages/packager/src/index.js",
    "file/packages/packager/src/index.js.html",
    "packages/packager/src/index.js",
    "file"
  ],
  [
    "packages/packager/test/__bootstrap.test.js",
    "file/packages/packager/test/__bootstrap.test.js.html",
    "packages/packager/test/__bootstrap.test.js",
    "file"
  ],
  [
    "packages/packager/test/hooks/build-lambda-package.test.js",
    "file/packages/packager/test/hooks/build-lambda-package.test.js.html",
    "packages/packager/test/hooks/build-lambda-package.test.js",
    "file"
  ],
  [
    "packages/packager/test/index.test.js",
    "file/packages/packager/test/index.test.js.html",
    "packages/packager/test/index.test.js",
    "file"
  ]
]